using Microsoft.AspNetCore.Mvc;
using warehouse_management_api_NourM.Contracts;
using warehouse_management_api_NourM.Models;

namespace warehouse_management_api_NourM.Controllers;

[ApiController]
[Route("api/products")]
public class ProductsController : ControllerBase
{
    //1. Get all products
    [HttpGet]
    public ActionResult GetProducts([FromQuery] bool onlyAvailable = false)
    {
        //The assumption for this method is that it will return only active products (where IsArchived = false)
        var products = new List<Product>();
        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (!p.IsArchived)
            {
                products.Add(p);
            }
        }
        
        //If the user specified that he wants only available products, we filter the products list
        //and keep only products that are in stock
        if (onlyAvailable)
        {
            var availableProducts  = new List<Product>();
            foreach (Product p in products)
            {
                if (p.QuantityInStock > 0)
                {
                    availableProducts.Add(p);
                }
            }
            products = availableProducts;
        }

        List<Product> toReturn = products
            .OrderByDescending(p => p.CreatedAt)
            .ToList();

        return Ok(toReturn);
    }
    
    //2. Get product by id
    [HttpGet("{id}")]
    public ActionResult GetProductById([FromRoute] string id)
    {
        //If the id is a valid GUID, we search the products list, else we return status code 400 (BadRequest) because the Id is not a valid GUID
        if(Guid.TryParse(id, out var guid))
        {
            foreach (Product p in FakeWarehouseStore.Products)
            {
                if (p.Id == id)
                {
                    return Ok(p);
                }
            }
            return NotFound("There is no product with the specified id");
        }

        return BadRequest("The entered Id is not a valid GUID");
    }
    
    //3. Search products 
    [HttpGet("search")]
    //The query parameters can be null, in case the user wants to provide one parameter only
    public ActionResult GetProductsBySearch([FromQuery] string? name, [FromQuery] string? supplier)
    {
        //If both parameters are empty, we return BadRequest
        if (string.IsNullOrWhiteSpace(name) && string.IsNullOrWhiteSpace(supplier))
        {
            return BadRequest("Please provide at least the item name or the supplier name.");
        }

        List<Product> result = new List<Product>();

        //We search all products and return those that match every search
        //filter the user provided (name, supplier, or both), while ignoring any filter that the user didn't provide.
        foreach (Product p in FakeWarehouseStore.Products)
        {
            bool matchesName = true;
            bool matchesSupplier = true;

            if (!string.IsNullOrWhiteSpace(name))
            {
                matchesName = p.Name.ToLower().Contains(name.ToLower());
            }

            if (!string.IsNullOrWhiteSpace(supplier))
            {
                matchesSupplier = p.SupplierName.ToLower().Contains(supplier.ToLower());
            }

            if (matchesName && matchesSupplier)
            {
                result.Add(p);
            }
        }

        return Ok(result);
    }
    
    //4. Create product
    [HttpPost]
    public ActionResult CreateProduct([FromBody] CreateProductRequest p)
    {
        foreach (Product product in FakeWarehouseStore.Products)
        {
            if (product.SKU.ToLower() == p.SKU.ToLower())
            {
                return BadRequest("A product with this SKU already exists.");
            }
        }
        // The request body is represented by the CreateProductRequest class, which contains
        // only the fields that the client is allowed to provide. The remaining fields are generated by the server, then the product is added.
        Product pr = new Product()
        {
            Id = Guid.NewGuid().ToString(),
            Name = p.Name,
            SKU = p.SKU,
            Description = p.Description,
            Price = p.Price,
            QuantityInStock = p.QuantityInStock,
            SupplierName = p.SupplierName,
            ExpiryDate = p.ExpiryDate,
            IsArchived = false,
            CreatedAt = DateTime.Now,
            LastUpdatedAt = DateTime.Now
        };
        FakeWarehouseStore.Products.Add(pr);
        return Ok("New product is added");
    }
    
    //5. Update quantity
    [HttpPost("{id}/quantity")]
    public ActionResult UpdateQuantity([FromRoute] string id, [FromBody] UpdateProductQuantityRequest quantity)
    {
        //Check if the Id provided is a valid GUID
        if (!Guid.TryParse(id, out var guid))
        {
            return BadRequest("The entered Id is not valid");
        }
        
        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.Id == id)
            {
                //The quantity cannot be negative since I added a validation attribute in the UpdateProductQuantityRequest class
                p.QuantityInStock = quantity.QuantityInStock;
                p.LastUpdatedAt = DateTime.Now;
                return Ok("Quantity in Stock Updated");
            }
            
        }
        return NotFound("There is no product with the specified id");
    }
}
    
