using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using warehouse_management_api_NourM.Contracts;
using warehouse_management_api_NourM.Models;

namespace warehouse_management_api_NourM.Controllers;

[ApiController]
[Route("api/products")]
public class ProductsController : ControllerBase
{
    //1. Get all products
    [HttpGet]
    public ActionResult GetProducts([FromQuery] bool onlyAvailable = false)
    {
        //The assumption for this method is that it will return only active products (where IsArchived = false)
        var products = new List<Product>();
        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (!p.IsArchived)
            {
                products.Add(p);
            }
        }
        
        //If the user specified that he wants only available products, we filter the products list
        //and keep only products that are in stock
        if (onlyAvailable)
        {
            var availableProducts  = new List<Product>();
            foreach (Product p in products)
            {
                if (p.QuantityInStock > 0)
                {
                    availableProducts.Add(p);
                }
            }
            products = availableProducts;
        }

        List<Product> toReturn = products
            .OrderByDescending(p => p.CreatedAt)
            .ToList();

        return Ok(toReturn);
    }
    
    //2. Get product by id
    [HttpGet("{id}")]
    public ActionResult GetProductById([FromRoute] string id)
    {
        //If the id is a valid GUID, we search the products list, else we return status code 400 (BadRequest) because the Id is not a valid GUID
        if(Guid.TryParse(id, out var guid))
        {
            foreach (Product p in FakeWarehouseStore.Products)
            {
                if (p.Id == id)
                {
                    return Ok(p);
                }
            }
            return NotFound("There is no product with the specified id");
        }

        return BadRequest("The entered Id is not a valid GUID");
    }
    
    //3. Search products 
    [HttpGet("search")]
    //The query parameters can be null, in case the user wants to provide one parameter only
    public ActionResult GetProductsBySearch([FromQuery] string? name, [FromQuery] string? supplier)
    {
        //If both parameters are empty, we return BadRequest
        if (string.IsNullOrWhiteSpace(name) && string.IsNullOrWhiteSpace(supplier))
        {
            return BadRequest("Please provide at least the item name or the supplier name.");
        }

        List<Product> result = new List<Product>();

        //We search all products and return those that match every search
        //filter the user provided (name, supplier, or both), while ignoring any filter that the user didn't provide.
        foreach (Product p in FakeWarehouseStore.Products)
        {
            bool matchesName = true;
            bool matchesSupplier = true;

            if (!string.IsNullOrWhiteSpace(name))
            {
                matchesName = p.Name.ToLower().Contains(name.ToLower());
            }

            if (!string.IsNullOrWhiteSpace(supplier))
            {
                matchesSupplier = p.SupplierName.ToLower().Contains(supplier.ToLower());
            }

            if (matchesName && matchesSupplier)
            {
                result.Add(p);
            }
        }

        return Ok(result);
    }
    
    //4. Create product
    [HttpPost]
    public ActionResult CreateProduct([FromBody] CreateProductRequest p)
    {
        foreach (Product product in FakeWarehouseStore.Products)
        {
            if (product.SKU.ToLower() == p.SKU.ToLower())
            {
                return BadRequest("A product with this SKU already exists.");
            }
        }
        // The request body is represented by the CreateProductRequest class, which contains
        // only the fields that the client is allowed to provide. The remaining fields are generated by the server, then the product is added.
        Product pr = new Product()
        {
            Id = Guid.NewGuid().ToString(),
            Name = p.Name,
            SKU = p.SKU,
            Description = p.Description,
            Price = p.Price,
            QuantityInStock = p.QuantityInStock,
            SupplierName = p.SupplierName,
            ExpiryDate = p.ExpiryDate,
            IsArchived = false,
            CreatedAt = DateTime.Now,
            LastUpdatedAt = DateTime.Now
        };
        FakeWarehouseStore.Products.Add(pr);
        return Ok("New product is added");
    }
    
    //5. Update quantity
    [HttpPost("{id}/quantity")]
    public ActionResult UpdateQuantity([FromRoute] string id, [FromBody] UpdateProductQuantityRequest req)
    {
        //Check if the Id provided is a valid GUID
        if (!Guid.TryParse(id, out var guid))
        {
            return BadRequest("The entered Id is not valid");
        }
        
        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.Id == id)
            {
                //The quantity cannot be negative since I added a validation attribute in the UpdateProductQuantityRequest class
                p.QuantityInStock = req.QuantityInStock;
                p.LastUpdatedAt = DateTime.Now;
                return Ok("Quantity in Stock Updated");
            }
            
        }
        return NotFound("There is no product with the specified id");
    }
    
    //6. Update Price
    [HttpPost("{id}/price")]
    public ActionResult UpdatePrice([FromRoute] string id, [FromBody] UpdateProductPriceRequest req)
    {
        //Check if the Id provided is a valid GUID
        if (!Guid.TryParse(id, out var guid))
        {
            return BadRequest("The entered Id is not valid");
        }
        
        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.Id == id)
            {
                //The quantity cannot be negative since I added a validation attribute in the UpdateProductQuantityRequest class
                //Logging (old vs new price)
                Console.WriteLine($"Price of {p.Name} updated from {p.Price} to {req.Price}");
                
                //After logging, we update the prices
                p.Price = req.Price;
                p.LastUpdatedAt = DateTime.Now;
                return Ok("Price Updated");
            }
            
        }
        return NotFound("There is no product with the specified id");
    }
    
    //7. Upload Image
    [HttpPost("{id}/image")]
    public async Task<ActionResult> UploadImage([FromRoute] string id, IFormFile image)
    {
        // Check if the Id provided is a valid GUID
        if (!Guid.TryParse(id, out var guid))
        {
            return BadRequest("The entered Id is not valid");
        }

        // Check if the product exists
        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.Id == id)
            {
                // Check if the uploaded file is empty
                if (image == null || image.Length == 0)
                {
                    return BadRequest("Please upload an image.");
                }

                // Check the image extension
                string extension = Path.GetExtension(image.FileName).ToLower();

                if (extension != ".jpg" &&
                    extension != ".jpeg" &&
                    extension != ".png")
                {
                    return BadRequest("Only JPG and PNG images are allowed.");
                }

                // Check the image size (maximum 2 MB)
                if (image.Length > 2 * 1024 * 1024)
                {
                    return BadRequest("Image size cannot exceed 2 MB.");
                }

                // Create the uploads folder if it doesn't exist
                string folder = "wwwroot/uploads";
                Directory.CreateDirectory(folder);

                // Save the image
                string path = Path.Combine(folder, image.FileName);

                using (FileStream stream = new FileStream(path, FileMode.Create))
                {
                    await image.CopyToAsync(stream);
                }

                return Ok("Image uploaded successfully.");
            }
        }

        return NotFound("There is no product with the specified id.");
    }

    //8. Delete product 
    [HttpDelete("{id}")]
    public ActionResult DeleteProduct([FromRoute] string id)
    {
        // Check if the Id provided is a valid GUID
        if (!Guid.TryParse(id, out var guid))
        {
            return BadRequest("The entered Id is not valid");
        }
        
        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.Id == id)
            {
                if (p.IsArchived)
                {
                    return Ok("Product is already deleted (archived)");
                }
                p.IsArchived = true;
                // Since the product is being archived (soft deleted), update the LastUpdatedAt property.
                p.LastUpdatedAt = DateTime.Now;
                return Ok("Product Deleted (Archived)");
            }
        }
        return NotFound("There is no product with the specified id.");
    }

    
    //9. Get warehouse server time
    [HttpGet("server-time")]
    public ActionResult GetServerTime([FromHeader(Name = "Accept-Language")] string language)
    {
        if (language != "en-US" &&
            language != "fr-FR" &&
            language != "ar-LB")
        {
            return BadRequest("The specified language is not supported");
        }
        CultureInfo culture;

        if (language == "fr-FR")
        {
            culture = new CultureInfo("fr-FR");
        }
        else if (language == "ar-LB")
        {
            culture = new CultureInfo("ar-LB");
        }
        else
        {
            culture = new CultureInfo("en-US");
        }

        string currentTime = DateTime.Now.ToString("F", culture);

        return Ok(currentTime);
    }
    
    // Task 2: Assigning supplier to product
    [HttpPost("{id}/assign-supplier/{supplierId}")]
    //// This method assigns the specified supplier to the specified product after validating that both exist and that the product is not archived.
    public ActionResult AssignSupplierToProduct(
        [FromRoute] string id,
        [FromRoute] string supplierId)
    {
        //First, we check if both ids are valid GUIDs
        if (!Guid.TryParse(id, out var guid))
        {
            return BadRequest("The product Id is not valid.");
        }

        if (!Guid.TryParse(supplierId, out _))
        {
            return BadRequest("The supplier Id is not valid.");
        }
        
        //Search for the product using its Id

        Product? product = null;

        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.Id == id)
            {
                product = p;
                break;
            }
        }

        if (product == null)
        {
            return NotFound("Product not found.");
        }

        if (product.IsArchived)
        {
            return BadRequest("Archived products cannot be assigned to a supplier.");
        }
        
        //Search for the supplier using their Id
        foreach (Supplier s in FakeSupplierStore.Suppliers)
        {
            if (s.Id == supplierId)
            {
                product.SupplierName = s.Name;
                product.LastUpdatedAt = DateTime.Now;

                return Ok("Supplier assigned to product.");
            }
        }

        return NotFound("Supplier not found.");
    }
    
    // Extra endpoints (Not mentioned in the lab)
    // 1- Restore archived product
    [HttpPost("{id}/restore")]
    public ActionResult RestoreProduct([FromRoute] string id)
    {
        if (!Guid.TryParse(id, out var guid))
        {
            return BadRequest("The entered Id is not valid");
        }

        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.Id == id)
            {
                if (!p.IsArchived)
                {
                    return Ok("Product is already active");
                }

                p.IsArchived = false;
                p.LastUpdatedAt = DateTime.Now;

                return Ok("Product restored successfully");
            }
        }

        return NotFound("There is no product with the specified id");
    }
    
    //2- Get low stock products
    // Returns all active products that are running low on stock based on the specified threshold (default value for the threshold is 5)
    [HttpGet("low-stock")]
    public ActionResult GetLowStockProducts([FromQuery] int threshold = 5)
    {
        List<Product> lowStockProducts = new List<Product>();

        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (!p.IsArchived && p.QuantityInStock <= threshold)
            {
                lowStockProducts.Add(p);
            }
        }

        return Ok(lowStockProducts);
    }
    
    // 3- Get general warehouse statistics about products.
    [HttpGet("statistics")]
    public ActionResult GetProductStatistics()
    {
        int totalProducts = FakeWarehouseStore.Products.Count;
        int activeProducts = 0;
        int archivedProducts = 0;
        int totalStock = 0;

        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.IsArchived)
            {
                archivedProducts++;
            }
            else
            {
                activeProducts++;
            }

            totalStock += p.QuantityInStock;
        }

        return Ok($"Total Products: {totalProducts}, Active Products: {activeProducts}, Archived Products: {archivedProducts}, Total Number of Products in Stock: {totalStock}");

    }
    
}
    
