using System.Globalization;
using warehouse_management_api_NourM.Contracts;
using warehouse_management_api_NourM.Models;

namespace warehouse_management_api_NourM.Services;

public class ProductService
{
    public List<Product> GetProducts(bool onlyAvailable)
    {
        //The assumption for this method is that it will return only active products (where IsArchived = false)
        var products = new List<Product>();

        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (!p.IsArchived)
            {
                products.Add(p);
            }
        }

        //If the user specified that he wants only available products, we filter the products list
        //and keep only products that are in stock
        if (onlyAvailable)
        {
            var availableProducts = new List<Product>();

            foreach (Product p in products)
            {
                if (p.QuantityInStock > 0)
                {
                    availableProducts.Add(p);
                }
            }

            products = availableProducts;
        }

        return products.OrderByDescending(p => p.CreatedAt).ToList();
    }

    public Product? GetProductById(string id)
    {
        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.Id == id)
            {
                return p;
            }
        }

        return null;
    }

    public List<Product> SearchProducts(string? name, string? supplier)
    {
        List<Product> result = new List<Product>();

        //We search all products and return those that match every search
        //filter the user provided (name, supplier, or both), while ignoring any filter that the user didn't provide.
        foreach (Product p in FakeWarehouseStore.Products)
        {
            bool matchesName = true;
            bool matchesSupplier = true;

            if (!string.IsNullOrWhiteSpace(name))
            {
                matchesName = p.Name.ToLower().Contains(name.ToLower());
            }

            if (!string.IsNullOrWhiteSpace(supplier))
            {
                matchesSupplier = p.SupplierName.ToLower().Contains(supplier.ToLower());
            }

            if (matchesName && matchesSupplier)
            {
                result.Add(p);
            }
        }

        return result;
    }

    public string CreateProduct(CreateProductRequest p)
    {
        foreach (Product product in FakeWarehouseStore.Products)
        {
            if (product.SKU.ToLower() == p.SKU.ToLower())
            {
                return "duplicate sku";
            }
        }

        // The request body is represented by the CreateProductRequest class, which contains
        // only the fields that the client is allowed to provide. The remaining fields are generated by the server, then the product is added.
        Product pr = new Product()
        {
            Id = Guid.NewGuid().ToString(),
            Name = p.Name,
            SKU = p.SKU,
            Description = p.Description,
            Price = p.Price,
            QuantityInStock = p.QuantityInStock,
            SupplierName = p.SupplierName,
            ExpiryDate = p.ExpiryDate,
            IsArchived = false,
            CreatedAt = DateTime.UtcNow,
            LastUpdatedAt = DateTime.UtcNow
        };

        FakeWarehouseStore.Products.Add(pr);
        return "created";
    }

    public string UpdateQuantity(string id, UpdateProductQuantityRequest req)
    {
        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.Id == id)
            {
                //The quantity cannot be negative since I added a validation attribute in the UpdateProductQuantityRequest class
                p.QuantityInStock = req.QuantityInStock;
                p.LastUpdatedAt = DateTime.UtcNow;
                return "updated";
            }
        }

        return "not found";
    }

    public string UpdatePrice(string id, UpdateProductPriceRequest req)
    {
        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.Id == id)
            {
                //Logging (old vs new price)
                Console.WriteLine($"Price of {p.Name} updated from {p.Price} to {req.Price}");

                //After logging, we update the prices
                p.Price = req.Price;
                p.LastUpdatedAt = DateTime.UtcNow;
                return "updated";
            }
        }

        return "not found";
    }

    public async Task<string> UploadImage(string id, IFormFile image)
    {
        // Check if the product exists
        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.Id == id)
            {
                // Check if the uploaded file is empty
                if (image == null || image.Length == 0)
                {
                    return "empty image";
                }

                // Check the image extension
                string extension = Path.GetExtension(image.FileName).ToLower();

                if (extension != ".jpg" &&
                    extension != ".jpeg" &&
                    extension != ".png")
                {
                    return "invalid extension";
                }

                // Check the image size (maximum 2 MB)
                if (image.Length > 2 * 1024 * 1024)
                {
                    return "too large";
                }

                // Create the uploads folder if it doesn't exist
                string folder = "wwwroot/uploads";
                Directory.CreateDirectory(folder);

                // Save the image
                string path = Path.Combine(folder, image.FileName);

                using (FileStream stream = new FileStream(path, FileMode.Create))
                {
                    await image.CopyToAsync(stream);
                }

                return "uploaded";
            }
        }

        return "not found";
    }

    public string DeleteProduct(string id)
    {
        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.Id == id)
            {
                if (p.IsArchived)
                {
                    return "already archived";
                }

                p.IsArchived = true;
                // Since the product is being archived (soft deleted), update the LastUpdatedAt property.
                p.LastUpdatedAt = DateTime.UtcNow;
                return "archived";
            }
        }

        return "not found";
    }

    public string GetServerTime(string language)
    {
        CultureInfo culture;

        if (language == "fr-FR")
        {
            culture = new CultureInfo("fr-FR");
        }
        else if (language == "ar-LB")
        {
            culture = new CultureInfo("ar-LB");
        }
        else
        {
            culture = new CultureInfo("en-US");
        }

        return DateTime.UtcNow.ToString("F", culture);
    }

    public string AssignSupplierToProduct(string id, string supplierId)
    {
        //Search for the product using its Id
        Product? product = null;

        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.Id == id)
            {
                product = p;
                break;
            }
        }

        if (product == null)
        {
            return "product not found";
        }

        if (product.IsArchived)
        {
            return "archived product";
        }

        //Search for the supplier using their Id
        foreach (Supplier s in FakeSupplierStore.Suppliers)
        {
            if (s.Id == supplierId)
            {
                product.SupplierName = s.Name;
                product.LastUpdatedAt = DateTime.UtcNow;

                return $"Supplier '{s.Name}' has been successfully assigned to the product '{product.Name}'";
            }
        }

        return "supplier not found";
    }

    public string RestoreProduct(string id)
    {
        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.Id == id)
            {
                if (!p.IsArchived)
                {
                    return "already active";
                }

                p.IsArchived = false;
                p.LastUpdatedAt = DateTime.UtcNow;
                return "restored";
            }
        }

        return "not found";
    }

    public List<Product> GetLowStockProducts(int threshold)
    {
        List<Product> lowStockProducts = new List<Product>();

        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (!p.IsArchived && p.QuantityInStock <= threshold)
            {
                lowStockProducts.Add(p);
            }
        }

        return lowStockProducts;
    }

    public string GetProductStatistics()
    {
        int totalProducts = FakeWarehouseStore.Products.Count;
        int activeProducts = 0;
        int archivedProducts = 0;
        int totalStock = 0;

        foreach (Product p in FakeWarehouseStore.Products)
        {
            if (p.IsArchived)
            {
                archivedProducts++;
            }
            else
            {
                activeProducts++;
            }

            totalStock += p.QuantityInStock;
        }

        return $"Total Products: {totalProducts}, Active Products: {activeProducts}, Archived Products: {archivedProducts}, Total Number of Products in Stock: {totalStock}";
    }
}