//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources_ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources_ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warehouse.Presentation.Resources.SharedResources.ar", typeof(SharedResources_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إرفاق صورة..
        /// </summary>
        internal static string EmptyImageViolation {
            get {
                return ResourceManager.GetString("EmptyImageViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يتجاوز حجم الصورة 2 ميغابايت..
        /// </summary>
        internal static string ImageSizeViolation {
            get {
                return ResourceManager.GetString("ImageSizeViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يُسمح فقط بصور بصيغتي JPG وPNG..
        /// </summary>
        internal static string ImageTypeViolation {
            get {
                return ResourceManager.GetString("ImageTypeViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم رفع الصورة بنجاح..
        /// </summary>
        internal static string ImageUploaded {
            get {
                return ResourceManager.GetString("ImageUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعرّف المُدخل غير صالح..
        /// </summary>
        internal static string InvalidID {
            get {
                return ResourceManager.GetString("InvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة غير مدعومة..
        /// </summary>
        internal static string LanguageNotSupported {
            get {
                return ResourceManager.GetString("LanguageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم أرشفة المنتج بنجاح.
        /// </summary>
        internal static string ProductArchived {
            get {
                return ResourceManager.GetString("ProductArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على المنتج..
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استعادة المنتج بنجاح..
        /// </summary>
        internal static string ProductRestored {
            get {
                return ResourceManager.GetString("ProductRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال اسم المنتج أو اسم المورّد على الأقل..
        /// </summary>
        internal static string SearchInputRequired {
            get {
                return ResourceManager.GetString("SearchInputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعيين المورد للمنتج بنجاح..
        /// </summary>
        internal static string SupplierAssigned {
            get {
                return ResourceManager.GetString("SupplierAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف المورّد بنجاح..
        /// </summary>
        internal static string SupplierDeleted {
            get {
                return ResourceManager.GetString("SupplierDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على المورد..
        /// </summary>
        internal static string SupplierNotFound {
            get {
                return ResourceManager.GetString("SupplierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ غير متوقع.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
